Locations = {
[0x0] = {"Minish Woods", {[0] = "Main", "N/A"}},
[0x1] = {"Minish Village", {[0] = "Main", "Side House Area", "N/A"}},
[0x2] = {"Hyrule Town", {[0] = "Main", "N/A"}},
[0x3] = {"Hyrule Field", {[0] = "Western Wood (South)", "Outside Link's House", "Exit from Minish Woods", "North from Minish Woods Exit", "Minish Woods Entrance & Farmers", "Lon Lon Ranch", "Outside Castle", "West Hyrule (Crenel)", "West Hyrule (Castor Wilds)", "Percy's House Area (Moblin)", "N/A"}},
[0x4] = {"Castor Wilds", {[0] = "Main", "N/A"}},
[0x5] = {"Wind Ruins", {[0] = "Entrance", "Beanstalk", "Triple Tektites", "Ladder to Tektites", "Minish & Fortress Entrance", "Armos & Beetle", "N/A"}},
[0x6] = {"Mount Crenel", {[0] = "Mountain Top (Jump to Rain)", "The Wall Climb", "Cave of Flames Entrance", "Gust Jar Shortcut", "Entrance", "N/A"}},
[0x7] = {"Hyrule Castle Garden", {[0] = "Main", "N/A"}},
[0x8] = {"Cloud Tops", {[0] = "Cloud Tops (House)", "Cloud Middles", "Cloud Bottoms", "N/A"}},
[0x9] = {"Royal Valley", {[0] = "Main", "Forest Maze", "N/A"}},
[0xa] = {"Veil Falls", {[0] = "Main", "N/A"}},
[0xb] = {"Lake Hylia", {[0] = "Main", "Beanstalk & Ladders", "N/A"}},
[0xc] = {"Caves", {[0] = "Minish Woods - Lake Hylia", "N/A"}},
[0xd] = {"Beanstalk", {[0] = "Mount Crenel Beanstalk", "Lake Hylia Beanstalk", "Wind Ruins Beanstalk", "Eastern Hills Beanstalk (Exit from Minish Woods)", "Western Woods (South) Beanstalk", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Mount Crenel Beanstalk Climb", "Lake Hylia Beanstalk Climb", "Wind Ruins Beanstalk Climb", "Eastern Hills Beanstalk Climb", "Western Woods Beanstalk Climb", "N/A"}},
[0xe] = {"Digging Cave", {[0] = "Hyrule Town", "N/A"}},
[0xf] = {"Melari's Mine", {[0] = "Main", "N/A"}},
[0x10] = {"Minish Paths", {[0] = "Minish Woods - Minish Village", "To Bow (Castor Wilds)", "Hyrule Town Schoolyard", "Lon Lon Ranch", "Lake Hylia - Mayor's Cabin", "N/A"}},
[0x11] = {"Crenel Minish Paths", {[0] = "Crenel Bean", "Crenel Water", "Rainfall", "To Melari's Mine", "N/A"}},
[0x12] = {"Digging Cave", {[0] = "Hyrule Field Farm", "N/A", "N/A", "Trilby Highlands", "N/A"}},
[0x13] = {"Digging Cave", {[0] = "Crenel Wall", "N/A"}},
[0x14] = {"Hyrule Town", {[0] = "Festival Room", "N/A"}},
[0x15] = {"Digging Cave", {[0] = "Veil Falls", "N/A"}},
[0x16] = {"Digging Cave", {[0] = "Castor Wilds", "N/A"}},
[0x17] = {"Fortress of Winds (Outside)", {[0] = "Entrance Hall", "2F", "3F", "Mole Mitts Room", "Small Key Spark Room", "N/A"}},
[0x18] = {"Digging Cave", {[0] = "Lake Hylia Middle Cave", "Lake Hylia Northern Cave", "N/A"}},
[0x19] = {"Veil Springs (Top)", {[0] = "Main", "N/A"}},
[0x1a] = {"Minish House Interiors", {[0] = "Minish Elder Gentari's House (Main)", "Minish Elder Gentari's House (Exit)", "House to Deepwood, Festari", "Red Minish House", "Green Minish House", "Blue Minish House", "Side Area House", "Shoe Minish House", "Pot Minish House", "Barrel Minish House", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Melari's Mines Southwest Room", "Melari's Mines Southeast Room", "Melari's Mines East Room", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Hyrule Field Southwest Minish House", "Hyrule Field Minish House Outside Link's House", "Hyrule Field Minish House next to Knuckle", "Lake Hylia Librari's House", "Hyrule Field Minish Woods Exit Minish House", "Hyrule Town Minish House", "Minish Woods Bomb Minish House", "Lake Hylia Ocarina Minish House", "N/A"}},
[0x1b] = {"House Green Interiors", {[0] = "Mayor's House", "Post Office", "Library 2F", "Library 1F", "Inn 1F", "Inn West Room", "Inn Middle Room", "Inn East Room", "Inn 2F West", "Inn 2F East", "Inn Minish Heart Piece", "School West", "School East", "N/A"}},
[0x1c] = {"House Wood Interiors", {[0] = "Stranger's House", "West Oracle House (Nayru?)", "West Oracle House (Farore?)", "West Oracle House (Din?)", "Dr. Left's House", "ナシ Unused Room", "Romio's House", "Julietta's House", "Percy's House", "East Oracle House (Nayru?)", "East Oracle House (Farore?)", "East Oracle House (Din?)", "Cucco House", "N/A", "N/A", "N/A", "Link's House (Entrance)", "Link's House (Smith)", "Dampe's House", "ナシ Unused Room", "Lake Hylia Stockwell's House", "Link's House 2F", "N/A"}},
[0x1d] = {"Hyrule Blue Interiors", {[0] = "Stockwell's Shop", "Cafe", "Rem's Shoe Shop", "Bakery", "Simon's Simulations", "Figurine Reward House", "Borlov Chest Game Entrance", "Carlov's Room", "Borlov Chest Game", "N/A"}},
[0x1e] = {"Tree Interiors", {[0] = "Witch Hut", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Stairs to Carlov", "Percy's Tree House (West Field)", "Heart Piece (Southeast from Link's House)", "Stairs to Blade Brother (Lake Hylia)", "Unused (Exits to Minish Woods Business Scrub)", "Stairs to Magic Boomerang (Northwest)", "Stairs to Magic Boomerang (Northeast)", "Stairs to Magic Boomerang (Southwest)", "Stairs to Magic Boomerang (Southeast)", "Heart Piece (Southwest Field)", "Stairs to Fairy Fountain (East of Magic Boomerang)", "Stairs to Minish Woods Wallet Fairy", "未 Unfinished Room", " Stairs to Business Scrub (Minish Woods)", "未 Unfinished Room", " Heart Container (Lake Hylia Minish House)"}},
[0x1f] = {"Blade Brothers", {[0] = "Grayblade (Mount Crenel)", "Splitblade (Veil Falls)", "Greatblade (North Hyrule)", "Scarblade (Castor Wilds North)", "Swiftblade I (Castor Wilds Grave)", "Grimblade (Castle Garden)", "Waveblade (Lake Hylia)", "ナシ Unused Room", "ナシ Unused Room", "ナシ Unused Room", "To Grimblade", "To Splitblade", "To Greatblade", "To Scarblade", "N/A"}},
[0x20] = {"Crenel Caves", {[0] = "Block Pushing/Helmasaur", "Pillar Cave", "Bridge Switch", "Exit to Melari's Mines entrance", "Grip Ring Business Scrub", "Fairy Fountain Heart Piece", "Spiny Chu Bomb Block Puzzle", "Chuchu Pot Chest", "Water Heart Piece", "15 Rupee Fairy Fountain", "Helmasaur Hallway (2F)", "Mushroom and Keese (1F)", "Ladder to Green Water", "Bomb Business Scrub", "Hermit's Cave", " Hint Scrub ", "To Grayblade", "N/A"}},
[0x21] = {"Minish Holes", {[0] = "Lon Lon Ranch, north", "Lake Hylia East Minish Hole House", "Hyrule Castle Garden, top right", "Mt. Crenel Minish Hole House", "Outside Hyrule Castle, East", "ナシ Unused Room", "Castor Wilds Bow Hole", "Wind Ruins Entrance Minish Hole House", "Minish Woods South Hole", "Castor Wilds North Hole", "Castor Wilds West Hole", "Castor Wilds Middle Hole", "Wind Ruins Tektite Room", "Castor Wilds Next to Bow Hole", "ナシ Unused Room", " ナシ Unused Room", "ナシ Unused Room", "ナシ Unused Room", "N/A"}},
[0x22] = {"House Tile Interiors", {[0] = "Carpenter House", "Swiftblade's House", "Ranch House West", "Ranch House East", "Farm House", "Lake Hylia Mayor's House", "N/A"}},
[0x23] = {"Great Fairy Fountains", {[0] = "Graveyard Quiver Fairy", "Minish Woods Wallet Fairy", "Mount Crenel Bomb Fairy", "N/A"}},
[0x24] = {"Castor Wilds Caves", {[0] = "South Gold Kinstone", "North Business Scrub & Gold Kinstone", "Wind Ruins Cave", "Darknut Cave Entrance", "Northeast Heart Piece Cave", "N/A"}},
[0x25] = {"Castor Wilds Darknut Cave", {[0] = "Darknut Room", "Hallway", "N/A"}},
[0x26] = {"Armos Interiors", {[0] = "Wind Ruins Entrance North", "Wind Ruins Entrance South", "Wind Ruins 4 Armos Leftmost", "Wind Ruins 4 Armos Middle left", "Wind Ruins 4 Armos Middle right", "Wind Ruins 4 Armos Rightmost", "Unused? (Exit from 05)", "Wind Ruins Minish Grass Path", "Unused? Wind Ruins Entrance, front of cave", "Fortress of Winds East Side Left Armos", "Fortress of Winds East Side Right Armos", "N/A"}},
[0x27] = {"Town House Minish", {[0] = "Mayor's House Hole", "West Oracle House Hole", "Dr. Left's House Hole", "Carpenter House Hole", "Cafe Hole", "Unused", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Library Bookshelf", "Librari's Book House", "Rem's Shoe Shop", "N/A"}},
[0x28] = {"House Roofs", {[0] = "Cafe Roof", "Stockwell's Roof", "Dr. Left's Roof", "Bakery Roof", "N/A"}},
[0x29] = {"Goron Cave", {[0] = "Stairs to Cave", "Main", "N/A"}},
[0x2a] = {"Wind Tribe Tower", {[0] = "Entrance", "Floor 2", "Floor 3", "Floor 4", "N/A"}},
[0x2b] = {"Entrance to Palace of Winds", {[0] = "Main", "N/A"}},
[0x2c] = {"Caves", {[0] = "Magic Boomerang", "To Graveyard", "Unused Spring Cave", "Unused Spring Cave", "Unused Bomb Block Cave", "Unused Bomb Block Cave", "Unused Block Cave", "Keese Chest Cave (Trilby Highlands)", "Fairy Fountain (Trilby Highlands)", "Fairy Fountain (Outside Link's House)", "Unused Water Cave", "Hyrule Town Waterfall", "Lon Lon Ranch Cave", "Lon Lon Ranch Secret Cave", "Trilby Highlands Cave", "Lon Lon Ranch Wallet", "75 Rupee Cave (Outside Link's House)", "75 Rupee Cave (Trilby Highlands)", "Fairy Fountain (Trilby Highlands Mole Mitts Cave)", "Keese Chest Cave (Southeast Hyrule)", "Bottle Business Scrub", "Heart Piece Hallway", "Fairy Fountain (Tree East of Magic Boomerang)", "Kinstone Business Scrub", "N/A"}},
[0x2d] = {"Veil Falls Caves", {[0] = "Helmasaur Keese Hallway 2F", "Helmasaur Keese Hallway 1F", "Helmasaur Keese Hallway Secret Room", "Entrance Cave", "Entrance Cave Exit", "Entrance Cave Secret Chest Room", "Entrance Cave Secret Staircases", "Entrance Cave Clone Block Puzzle", "Water Rupee Path", "Waterfall Heart Piece Cave", "N/A"}},
[0x2e] = {"Graveyard Caves", {[0] = "Heart Piece Grave", "Gina Grave", "N/A"}},
[0x2f] = {"Minish Caves", {[0] = "Mount Crenel Bean Plant Pesto Cave", "Castor Wilds Southeast Water 1", "Castor Wilds Southeast Water 2", "Wind Ruins Minish Cave", "Outside Link's House, Water Cave", "Minish Woods North Cave 1", "Minish Woods North Cave 2", "Lake Hylia North Cave", "Lake Hylia, Cave to Librari's House", "Minish Woods Southwest Caves", "N/A"}},
[0x30] = {"Castle Garden Minish Holes", {[0] = "East Fountain Hole", "West Fountain Hole", "N/A"}},
[0x31] = {"Castle Garden Minish Holes", {[0] = "Unused", "Unused", "N/A"}},
[0x32] = {"Ezlo's Room", {[0] = "Ezlo's Room", "N/A"}},
[0x33] = {"Castle Underground Test Dungeon", {[0] = "Top Left Room", "Top Room", "Top Right Room", "Left Room", "Middle Room", "Right Room", "Bottom Right Room", "Bottom Room", "Bottom Left Room", "N/A"}},
[0x34] = {"Hyrule Town Well", {[0] = "Main", "Well Entrance", "N/A"}},
[0x35] = {"Castle Garden Fountain Stairs", {[0] = "East Heart Piece", "West Fairy Fountain", "N/A"}},
[0x36] = {"Castle Garden Underground", {[0] = "Entrance", "Exit to Castle", "N/A"}},
[0x37] = {"Simon's Simulations", {[0] = "Main", "N/A"}},
[0x38] = {"Pillar Test Room", {[0] = "Main", "N/A"}},
[0x39] = {"Cave Test Dungeon", {[0] = "Top Left Room", "Top Room", "Top Right Room", "Left Room", "Middle Room", "Right Room", "Middle Bottom Room", "Bottom Middle", "N/A"}},
[0x3a] = {"Clone Test Cave", {[0] = "Entrance", "Middle", "End", "N/A"}},
[0x3b] = {"Deepwood Shrine", {[0] = "Madderpillar", "Pre-Madderpillar, Blue Portal", "Stairs to B1", "Pot Bridge Room", "Double Statue Room", "Map & Heart Piece Room", "Barrel Room", "Button & Mushrooms", "Mulldozer Fight", "Pillars & Slugs", "Lever & Mushroom", "Entrance Room", "N/A", "N/A", "N/A", "N/A", "Slug & Torch Room", "Boss Key Room", "Compass Room", "Unused", "Lily Pad West", "Lily Pad East", "Softlock", "Pre-Boss Room", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Inside Barrel", "N/A"}},
[0x3c] = {"Deepwood Shrine Boss Room", {[0] = "Main", "N/A"}},
[0x3d] = {"Outside Deepwood Shrine", {[0] = "Main", "N/A"}},
[0x3e] = {"Deepwood Shrine Test Room", {[0] = "Main", "N/A"}},
[0x3f] = {"Cave of Flames", {[0] = "Room After Cane", "Spiny Chu Room", "Cart to Spiny Chu", "Entrance Room", "Main Cart", "North from Entrance", "Cart West", "Helmasaur Fight", "Rollobite Lava Room", "Minish Lava Room", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Minish Spike Trap Room", "Four Rollobite Switch Room", "Hole to Gleerok", "Path to Boss Key", "Path to Boss Key 2", "Compass Room", "Bob-omb Cracked Wall Room", "Boss Door & Boss Key Room", "N/A"}},
[0x40] = {"Cave of Flames Boss Room", {[0] = "Main", "N/A"}},
[0x41] = {"Cave of Flames Test Room", {[0] = "Main", "N/A"}},
[0x42] = {"Fortress of Winds", {[0] = "Double Eyegore", "Before Mazaal", "East Side Key Lever", "Pit Platforms", "West Side Key Lever", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Darknut Room", "Arrow Eye Bridge to Darknut", "North Split Path Pit", "Wallmaster Minish Portal", "Pillar Clone Buttons", "Rotating Spike Traps after Darknut", "Mazaal", "West Side Stalfos Fight", "West Side Eye/Entrance to Mole Mitts Room", "2F Main Room", "Wallmaster Minish Hole to Small Key", "Boss Key", "West Side Stairs 2F", "East Side Stairs 2F", "N/A", "N/A", "West Side Stairs 1F", "Center Stairs 1F", "East Side Stairs 1F", "West Wizzrobe Fight Room", "East Heart Piece Room", "N/A"}},
[0x43] = {"Top of Fortress", {[0] = "Main", "N/A"}},
[0x44] = {"Inside Mazaal", {[0] = "Other Phases", "Phase 1", "N/A"}},
[0x45] = {"Fortress of Winds Test Room", {[0] = "Main", "N/A"}},
[0x46] = {"Temple of Droplets", {[0] = "West Hole to Boss Key", "North Split Room", "East Hole to Key", "Entrance Room", "Stairs to Northwest Lever", "Scissors Beetle Miniboss Room", "West Waterfall Northwest", "West Waterfall Northeast", "Waifu & Element", "Ice Corner to East", "Ice Pit Maze", "Hole to Blue Chuchu Key", "West Waterfall Southeast", "West Waterfall Southwest", "Big Octo Room", "Room to Big Blue Chuchu", "Big Blue Chuchu Room", "Big Blue Chuchu Key", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Boss Key Room", "North Small Key Room", "Block Clone Button Puzzle", "Block Clone Puzzle", "Block Clone Ice Bridge", "Stairs to Scissors Beetle Miniboss Room", "Spike Bar Flipper Room after 9 Lanterns", "9 Lanterns", "Lilypad Ice Blocks", "1 Frame Roll Pit", "Mulldozers & Fire Bars", "Dark Lantern Maze", "Twin Madderpillars", "After Twin Madderpillars", "Blue Chuchu Key Lever", "Mulldozer Key Room", "Bomb Wall to Twin Madderpillars", "Lilypad B2 West", "Compass Room to 4 Lanterns", "4 Lantern Scissors Beetles", "Lilypad B2 Middle", "Lilypad B2 East Madderpillar", "Flamebar Block Puzzle", "N/A"}},
[0x47] = {"Unused (Outside Droplets?)", {[0] = "Main", "N/A"}},
[0x48] = {"Hyrule Town Sewer (Bracelets)", {[0] = "Entrance", "North Room", "Pacci Jump Room", "Blue Mulldozer Fight", "West Chest Room", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "Flippers Room", "Librari Trapdoor Entrance", "West Frozen Chest", "Cross Intersection", "Southeast Corner", "Entrance", "N/A"}},
[0x49] = {"Temple of Droplets Test Room", {[0] = "Broken Room", "N/A"}},
[0x4a] = {"Royal Crypt", {[0] = "King Gustaf's Room", "Water Rope Hallway", "Gibdo Fight", "Unused Clone Button Room", "Key Block Room", "Unused Block Room", "Unused Door Hall", "Mushroom Pit", "Entrance", "N/A"}},
[0x4b] = {"Royal Crypt Test Room", {[0] = "Main", "N/A"}},
[0x4c] = {"Palace of Winds", {[0] = "Tornado to Gyorg Pair", "Boss Key Room", "Before Ball and Chain Soldiers", "Boss Door to Gyorg", "East Chest from Gyorg Boss Door", "Moblin & Wizzrobe Fight", "4 Button Stalfos", "Fan & Small Key to Boss Key", "Ball and Chain Soldiers", "Bombarossa Path", "Hole to Red Darknut Miniboss", "To Bombarossa Path", "Red Darknut Miniboss Fight", "Bombable Wall to Outside", "Bombable Walls Outside", "Cloud Jumps to Ball and Chain Soldiers", "Block Maze to Boss Door", "Cracked Floor Lakitu Jumps", "Bridge to Heart Piece", "Bridge Fan Floor Spike Room", "To Bridge Fan Floor Spike Room", "Red Portal Hall", "Platform Clone Ride to Block", "Pit Corner after Switch Small Key", "Platform Crow Ride", "Grate Platform Ride", "Spike Bar Minish Pot Maze", "Floormaster Lever Room", "Fire Wizzrobe Map Room", "Corner to Fire Wizzrobe Map Room", "Stairs after Floormaster Lever", "Hole to Kinstone Wizzrobe Fight", "Key Arrow Button from Minish", "Grates to 3F", "Spiny Fight & Fan Path", "Peahat Switch Cracked Floor Room", "Whirlwind Bombarossa Room", "Door to Stalfos Fire Bar Room", "Stalfos Fire Bar Hole to Small Key", "Shortcut Door Buttons", "To Peahat Switch Cracked Floor Room", "Kinstone Wizzrobe Fight", "Gibdo Stairs", "Spike Bar Small Key", "Roc's Cape Room", "Fire Bar Grates", "Platform Ride Bombarossas", "Bridge after Red Darknut Miniboss", "Bridge Switches & Clone Block", "Entrance Room", "Dark Compass Hall", "N/A"}},
[0x4d] = {"Palace of Winds Boss Room", {[0] = "Main", "N/A"}},
[0x4e] = {"Palace of Winds Test Room", {[0] = "---", "---"}},
[0x4f] = {"Elemental Sanctuary", {[0] = "Hall", "Main", "Stained Glass", "N/A"}},
[0x50] = {"Elemental Sanctuary Test Room", {[0] = "Main", "N/A"}},
[0x51] = {"Hyrule Castle", {[0] = "Entrance Room", "Halls", "Throne Room", "Basement Halls", "Throne Bed Room", "N/A"}},
[0x52] = {"Hyrule Castle", {[0] = "Garden to Elemental Sanctuary", "N/A"}},
[0x53] = {"Hyrule Castle Test Room", {[0] = "Main", "N/A"}},
[0x54] = {"Dark Hyrule Castle", {[0] = "Entrance Room", "Top Left Corner Key Chest", "Top Right Corner Key Chest", "Bottom Left Corner Key Chest", "Bottom Right Corner Key Chest", "Keaton Hall to Vaati", "Triple Darknut Fight", "Top Left Stairs Corner", "Top Left Eye Fire Bar", "Boss Key Room", "Darknut Miniboss to Boss Key", "Top Right Ghini Fight", "8 Lantern Fire Bar", "Top Right Stairs Corner", "Top Left Darknut Fight", "Sparks to Darknut Miniboss", "Top Right Twin Darknut Fight", "Bomb Block Grate Switches", "East Clone Block & Grate", "Bottom Left Darknut Fight", "Ball and Chain Soldier Boss Door Room", "Bottom Right Corner Darknut Fight", "Bottom Left Floor Tile Puzzle", "Entrance to Boss Door Section", "Clone Buttons to Bottom Right Stairs Corner", "Bottom Left Stairs Corner", "Bottom Left Ghini Fight", "Empty room?", "Basement, North", "Bottom Right Stairs Corner", "Top Left Corner Gibdo Room", "Throne Room Darknut", "Compass Room", "Moldorm Stairs", "Entrance to Throne Room", "Floormasters", "Floor Tiles", "Moblin Corner to Key", "Cannons", "Spike Trap Clone Buttons", "Corner to Cannon", "Entrance Hall to 1F Small Key", "Corner from Small Key", "Bottom Left Corner Pot Room", "Bottom Left Corner Gibdo Room", "Dark Gibdo Hall West", "Dark Gibdo Hall East", "Stairs to Throne Room", "Stairs to Prison", "Minish Portal & Fire Bars", "Purple Keaton Room", "Basement West Firebars", "Basement East Cannons", "Basement West Hall", "Basement East Hall", "Basement, South", "Prison, West", "Prison, East", "Prison, South"}},
[0x55] = {"Dark Hyrule Castle (Outside)", {[0] = "Zelda Statue Platform", "Garden to Elemental Sanctuary", "Outside, Northwest", "Outside, Northeast", "Outside, East", "Outside, Southwest", "Outside, South", "Outside, Southeast", "N/A"}},
[0x56] = {"Vaati's Wrath Hand Rooms", {[0] = "First Hand", "Second Hand", "Unused", "N/A"}},
[0x57] = {"Dark Hyrule Castle", {[0] = "Vaati's Wrath", "N/A"}},
[0x58] = {"Dark Hyrule Castle", {[0] = "Vaati Transfigured", "N/A"}},
[0x59] = {"Dark Hyrule Castle", {[0] = "First Hallway to Vaati 1", "N/A"}},
[0x5a] = {"Dark Hyrule Castle Test Room", {[0] = "Main", "N/A"}},
[0x5b] = {"N/A", {[0] = "N/A"}},
[0x5c] = {"N/A", {[0] = "N/A"}},
[0x5d] = {"N/A", {[0] = "N/A"}},
[0x5e] = {"N/A", {[0] = "N/A"}},
[0x5f] = {"N/A", {[0] = "N/A"}},
[0x60] = {"N/A", {[0] = "N/A"}},
[0x61] = {"N/A", {[0] = "N/A"}},
[0x62] = {"N/A", {[0] = "N/A"}},
[0x63] = {"N/A", {[0] = "N/A"}},
[0x64] = {"N/A", {[0] = "N/A"}},
[0x65] = {"N/A", {[0] = "N/A"}},
[0x66] = {"N/A", {[0] = "N/A"}},
[0x67] = {"N/A", {[0] = "N/A"}},
[0x68] = {"N/A", {[0] = "N/A"}},
[0x69] = {"N/A", {[0] = "N/A"}},
[0x6a] = {"N/A", {[0] = "N/A"}},
[0x6b] = {"N/A", {[0] = "N/A"}},
[0x6c] = {"N/A", {[0] = "N/A"}},
[0x6d] = {"N/A", {[0] = "N/A"}},
[0x6e] = {"N/A", {[0] = "N/A"}},
[0x6f] = {"N/A", {[0] = "N/A"}},
[0x70] = {"N/A", {[0] = "N/A"}},
[0x71] = {"N/A", {[0] = "N/A"}},
[0x72] = {"N/A", {[0] = "N/A"}},
[0x73] = {"N/A", {[0] = "N/A"}},
[0x74] = {"N/A", {[0] = "N/A"}},
[0x75] = {"N/A", {[0] = "N/A"}},
[0x76] = {"N/A", {[0] = "N/A"}},
[0x77] = {"N/A", {[0] = "N/A"}},
[0x78] = {"N/A", {[0] = "N/A"}},
[0x79] = {"N/A", {[0] = "N/A"}},
[0x7a] = {"N/A", {[0] = "N/A"}},
[0x7b] = {"N/A", {[0] = "N/A"}},
[0x7c] = {"N/A", {[0] = "N/A"}},
[0x7d] = {"N/A", {[0] = "N/A"}},
[0x7e] = {"N/A", {[0] = "N/A"}},
[0x7f] = {"N/A", {[0] = "N/A"}},
[0x80] = {"N/A", {[0] = "N/A"}},
[0x81] = {"N/A", {[0] = "N/A"}},
[0x82] = {"N/A", {[0] = "N/A"}},
[0x83] = {"N/A", {[0] = "N/A"}},
[0x84] = {"N/A", {[0] = "N/A"}},
[0x85] = {"N/A", {[0] = "N/A"}},
[0x86] = {"N/A", {[0] = "N/A"}},
[0x87] = {"N/A", {[0] = "N/A"}},
[0x88] = {"N/A", {[0] = "N/A"}},
[0x89] = {"N/A", {[0] = "N/A"}},
[0x8a] = {"N/A", {[0] = "N/A"}},
[0x8b] = {"N/A", {[0] = "N/A"}},
[0x8c] = {"N/A", {[0] = "N/A"}},
[0x8d] = {"N/A", {[0] = "N/A"}},
}